name: Auth Workflow - Build

on:
  push:
    branches:
      - master
    paths:
      - "packages/services/auth/**"

jobs:
  auth-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Auth
        uses: actions/checkout@v3

      - name: Navigate to  Auth directory
        run: cd packages/services/auth
        shell: bash

      - name: Setup Node v20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Success Build
        run: echo "Success Build"

      - name: Fail Build
        if: ${{ failure() }}
        run: echo "Fail Build"
