name: Project Init

on:
  release:
    types: [published]

jobs:
  project-init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Project Init ok
        run: echo "ok, project init successful"
