name: Docker Image Publish

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo from GitHub
        uses: actions/checkout@v4
      - name: Log in to Docker Hub using Docker CLI
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract Meta Data Information
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: zobaidulkazihub/purrrescue
      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: success
        run: echo "Success" && exit 0

      - name: failure
        run: echo "Failure" && exit 1
