name: User Workflow

on:
  push:
    branches:
      - main

jobs:
  user-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Navigate to  User directory
        run: cd packages/services/user

      - name: ls - a
        run: ls -a

      - name: message
        run: echo "Hello World"

      # - name: Setup Node v20
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 20
      #     cache: "yarn"

      # - name: Install dependencies
      #   run: yarn --frozen-lockfile

      # - name: Build
      #   run: yarn build

      # - name: Success Build
      #   run: echo "Success Build"
