name: User Workflow

on: [push, pull_request]

jobs:
  user-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: "../../packages/services/user/package.json"
      - name: devlopment build
        run: yarn build
        working-directory: "../../packages/services/user/package.json"

      - name: success build
        run: exit 0
